# Generated by Django 5.2.4 on 2025-07-22 06:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('expense', 'Expense')], max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_api', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
